{{- if index .Values "rbac" "create" -}}
{{- if eq (index .Values "watchNamespace") "*" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kubernetes-auto-ingress.fullname" . }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubernetes-auto-ingress.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubernetes-auto-ingress.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "kubernetes-auto-ingress.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
{{- else -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kubernetes-auto-ingress.fullname" . }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kubernetes-auto-ingress.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubernetes-auto-ingress.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "kubernetes-auto-ingress.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}