apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-ingress
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-ingress
  template:
    metadata:
      labels:
        app: auto-ingress
    spec:
      containers:
      - name: auto-ingress
        image: maayanlab/auto-ingress:latest
        imagePullPolicy: Always
        tty: true
      restartPolicy: Always
      serviceAccount: tiller
