apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-auto-ingress-service-account
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-auto-ingress-role
  namespace: kube-system
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-auto-ingress-role-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: kubernetes-auto-ingress-service-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kubernetes-auto-ingress-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-auto-ingress
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-auto-ingress
  template:
    metadata:
      labels:
        app: kubernetes-auto-ingress
    spec:
      containers:
      - name: kubernetes-auto-ingress
        image: maayanlab/kubernetes-auto-ingress:v1.2.6
        imagePullPolicy: Always
        tty: true
      restartPolicy: Always
      serviceAccount: kubernetes-auto-ingress-service-account
