rbac:
  create: true

serviceAccount:
  create: true
  name:

annotationKey: maayanlab.cloud/ingress

extraAnnotations:
  http:
    ingress:
      nginx.ingress.kubernetes.io/ssl-redirect": "false"
      traefik.ingress.kubernetes.io/router.entrypoints: web
  https:
    ingress:
      kubernetes.io/tls-acme: true
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # cert-manager.io/cluster-issuer: cluster-issuer

# for deployment namespace
watchNamespace:
# for all namespaces
# watchNamespace: '*'
